export enum ValidateProfileError {
  AGE_EMPTY = 'AGE_EMPTY',
  AGE_RANGE_LESS = 'AGE_RANGE_LESS',
  AVATAR_EMPTY = 'AVATAR_EMPTY',
  AVATAR_INVALID_URL = 'AVATAR_INVALID_URL',
  NAME_EMPTY = 'NAME_EMPTY',
  NAME_RANGE = 'NAME_RANGE',
  POSITION_EMPTY = 'POSITION_EMPTY',
  POSITION_RANGE_LESS = 'POSITION_RANGE_LESS',
}
