export enum ValidateProfileError {
  AGE_EMPTY = 'AGE_EMPTY',
  AGE_RANGE_LESS = 'AGE_RANGE_LESS',
  AVATAR_EMPTY = 'AVATAR_EMPTY',
  AVATAR_INVALID_URL = 'AVATAR_INVALID_URL',
  POSITION_EMPTY = 'POSITION_EMPTY',
  POSITION_RANGE_LESS = 'POSITION_RANGE_LESS',
}
