name: FRONTEND FLOW CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm i

      - name: run stylelint
        run: npm run test:stylelint
        if: always()

      - name: run eslint
        run: npm run test:eslint
        if: always()

      - name: run jest
        run: npm run test:jest
        if: always()
